strictPeerDependencies: true
blockExoticSubdeps: true
engineStrict: true
lockfile: true
color: true
loglevel: info
savePrefix: ""
allowBuilds:
  "@monadiam/shared@https://codeload.github.com/MonadIAM/shared/tar.gz/4b9e6d45dbcd870beef085c0f43754e608c0f059": true
  "msgpackr-extract": true
  "unrs-resolver": true
  "@scarf/scarf": false
  "protobufjs": true
  "esbuild": true
