strictPeerDependencies: true
blockExoticSubdeps: true
engineStrict: true
lockfile: true
color: true
loglevel: info
savePrefix: ""
allowBuilds:
  "@monadiam/shared@https://codeload.github.com/MonadIAM/shared/tar.gz/42a83dcc119887769a96ab510c96f9764a4e4fd5": true
  "@launchql/protobufjs": true
  "msgpackr-extract": true
  "unrs-resolver": true
  "@scarf/scarf": false
  "cpu-features": true
  "protobufjs": true
  "esbuild": true
  "ssh2": true
