strictPeerDependencies: true
blockExoticSubdeps: true
engineStrict: true
lockfile: true
color: true
loglevel: info
savePrefix: ""
allowBuilds:
  "@monadiam/shared@https://codeload.github.com/MonadIAM/shared/tar.gz/cc29b6976820b409490bfd655262e4e687272c5f": true
  "msgpackr-extract": true
  "unrs-resolver": true
  "@scarf/scarf": false
  "protobufjs": true
  "esbuild": true
