export enum ErrorKind {
    FOREIGN_KEY_VIOLATION = "foreign_key_violation",
    CONNECTION_ERROR = "database_connection_error",
    NOT_NULL_VIOLATION = "not_null_violation",
    UNIQUE_VIOLATION = "unique_violation",
    DEADLOCK = "database_deadlock",
    TIMEOUT = "database_timeout",
    NOT_FOUND = "not_found",
    INVARIANT_VIOLATION = "invariant_violation",
    EXTERNAL_SERVICE_FAILED = "external_service_failed",
    EXTERNAL_AUTHN_FAILED = "external_authn_failed",
    UNPROCESSABLE = "unprocessable",
    UNAUTHORIZED = "unauthorized",
    BAD_REQUEST = "bad_request",
    METHOD_NOT_ALLOWED = "method_not_allowed",
    FORBIDDEN = "forbidden",
    CONFLICT = "conflict",
    INTERNAL = "internal",
}

export enum ErrorCode {
    FOREIGN_KEY_VIOLATION = "foreign_key_violation",
    CONNECTION_ERROR = "database_connection_error",
    NOT_NULL_VIOLATION = "not_null_violation",
    UNIQUE_VIOLATION = "unique_violation",
    DEADLOCK = "database_deadlock",
    TIMEOUT = "database_timeout",
    NOT_FOUND = "not_found",
    INVARIANT_VIOLATION = "invariant_violation",
    EXTERNAL_SERVICE_FAILED = "external_service_failed",
    EXTERNAL_AUTHN_FAILED = "external_authn_failed",
    UNPROCESSABLE = "unprocessable",
    UNAUTHORIZED = "unauthorized",
    BAD_REQUEST = "bad_request",
    FORBIDDEN = "forbidden",
    CONFLICT = "conflict",
    INTERNAL = "internal",
    CORS_ORIGIN_REQUIRED = "cors_origin_required",
    CORS_ORIGIN_FORBIDDEN = "cors_origin_forbidden",
    METHOD_NOT_ALLOWED = "method_not_allowed",
}
