/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "commands": {
        "channel": {
            "SOUND_TOGGLED": string;
            "IN_APP_CHANNEL_NOT_FOUND": string;
        };
        "recipient": {
            "UPDATED": string;
            "OTP_CHANNEL_SELECTED": string;
        };
        "preference": {
            "TOGGLED": string;
            "CATEGORY_NOT_CONFIGURABLE": string;
            "CHANNEL_NOT_CONFIGURABLE": string;
        };
        "message": {
            "READ": string;
            "NOT_FOUND": string;
        };
    };
    "db": {
        "NOT_FOUND": string;
        "UNIQUE_VIOLATION": string;
        "FK_VIOLATION": string;
        "NOT_NULL_VIOLATION": string;
        "DEADLOCK": string;
        "LOCK_TIMEOUT": string;
        "CONNECTION_LOST": string;
        "INTERNAL_DRIVER_ERROR": string;
    };
    "entities": {
        "channel": {
            "ALREADY_VERIFIED": string;
            "SOUND_NOT_APPLICABLE": string;
        };
        "recipient": {
            "NO_CHANGES_DETECTED": string;
            "EMPTY_UPDATE_PATCH": string;
            "NOT_OWN_CHANNEL": string;
            "CHANNEL_NOT_VERIFIED": string;
            "UNSUPPORTED_OTP_CHANNEL_TYPE": string;
        };
        "message": {
            "CANNOT_SEND_FROM_STATE": string;
            "CANNOT_DELIVER_FROM_STATE": string;
            "CANNOT_FAIL_DELIVERED": string;
            "READ_STATE_IN_APP_ONLY": string;
            "ALREADY_READ": string;
        };
    };
    "global": {
        "throttle": string;
    };
    "guard": {
        "permission": {
            "ACCOUNT_REQUIRED": string;
            "REALM_REQUIRED": string;
            "REALM_SCOPE_MISSING": string;
            "REALM_OUT_OF_SESSION_SCOPE": string;
            "GLOBAL_SCOPE_REQUIRES_DIRECT_LOGIN": string;
            "INSUFFICIENT_PERMISSIONS": string;
        };
        "authn": {
            "TOKEN_MISSING": string;
            "MALFORMED_AUTHORIZATION": string;
            "SESSION_REVOKED": string;
        };
        "reauthentication": {
            "REAUTHENTICATION_REQUIRED": string;
            "NOT_AUTHENTICATED": string;
        };
    };
    "services": {
        "jwt": {
            "INVALID_ACCESS_TOKEN": string;
        };
        "vault": {
            "REQUEST_FAILED": string;
            "INVALID_SIGNATURE": string;
        };
    };
    "templates": {
        "IDENTIFIER_VERIFICATION_OTP": {
            "subject": string;
            "body": string;
        };
        "ACCOUNT_VERIFICATION_OTP": {
            "subject": string;
            "body": string;
        };
        "RESET_PASSWORD_OTP": {
            "subject": string;
            "body": string;
        };
        "LOGIN_OTP": {
            "subject": string;
            "body": string;
        };
        "LOGIN_ALERT": {
            "subject": string;
            "body": string;
        };
        "PASSWORD_CHANGED": {
            "subject": string;
            "body": string;
        };
        "PASSWORD_CHANGED_VIA_OTP": {
            "subject": string;
            "body": string;
        };
        "PASSWORD_CHANGED_VIA_RECOVERY_CODE": {
            "subject": string;
            "body": string;
        };
        "IDENTIFIER_PURGED": {
            "subject": string;
            "body": string;
        };
        "SECOND_FACTOR_ENABLED": {
            "subject": string;
            "body": string;
        };
        "SECOND_FACTOR_RESET": {
            "subject": string;
            "body": string;
        };
        "RECOVERY_CODES_REGENERATED": {
            "subject": string;
            "body": string;
        };
        "INVITE_RECEIVED": {
            "subject": string;
            "body": string;
        };
        "INVITE_CANCELLED": {
            "subject": string;
            "body": string;
        };
        "ASSIGNMENT_GRANTED": {
            "subject": string;
            "body": string;
        };
        "ASSIGNMENT_REVOKED": {
            "subject": string;
            "body": string;
        };
        "REALM_EXCLUDED": {
            "subject": string;
            "body": string;
        };
    };
    "validator": {
        "REQUIRED": string;
        "IS_OBJECT": string;
        "IS_STRING": string;
        "LENGTH": string;
        "MIN_LENGTH": string;
        "MAX_LENGTH": string;
        "ARRAY_MIN_SIZE": string;
        "ARRAY_MAX_SIZE": string;
        "MATCHES": string;
        "IS_EMAIL": string;
        "IS_UUID": string;
        "IS_PHONE": string;
        "IS_NUMBER": string;
        "IS_INT": string;
        "IS_POSITIVE": string;
        "MIN": string;
        "MAX": string;
        "IS_DECIMAL": string;
        "IS_BOOLEAN": string;
        "IS_DATE": string;
        "IS_ENUM": string;
        "IS_ARRAY": string;
        "ARRAY_UNIQUE": string;
        "NESTED": string;
        "IS_IN": string;
        "IS_ORDINAL": string;
        "NOT_EQUAL_TO": string;
        "IS_MS_STRING": string;
        "COMMON_ERROR": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
